version: "3.8"
services:
  php:
    build: .
    environment:
      DATABASE_URL: "mysql://root:team@db/team"
    depends_on:
      - db
      - maildev
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: team
      MYSQL_USER: team
      MYSQL_PASSWORD: team
      MYSQL_ROOT_PASSWORD: team

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  maildev:
    image: djfarrelly/maildev:1.1.0
    depends_on:
      - db
    ports:
      - 1080:80

volumes:
  db-data: